// Build a lucide SUBSET for this site.
//
// The full vendor library is 409KB (~100KB on the wire) and ships on every page
// for the ~80 icons we actually use. This script scans the source + the built
// route HTML for every icon name referenced, pulls just those definitions out of
// the vendor bundle, and emits assets/vendor/lucide-subset.js — a drop-in that
// exposes the same window.lucide.createIcons() API the app calls.
//
// Run: node scripts/build-icons.mjs   (before npm run bundle; part of npm run make)
import { readFile, writeFile, readdir, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const VENDOR = 'assets/vendor/lucide-1.21.0.min.js';
const OUT = 'assets/vendor/lucide-subset.js';

// ---- 1. collect every icon name the site can reference
const names = new Set();
const addFrom = (text) => {
  for (const m of text.matchAll(/data-lucide="([a-z0-9-]+)"/g)) names.add(m[1]);
  for (const m of text.matchAll(/lucide lucide-([a-z0-9-]+)/g)) names.add(m[1]);
  // dynamic: data-lucide={ic} fed from config tuples/objects
  for (const m of text.matchAll(/icon:\s*'([a-z0-9-]+)'/g)) names.add(m[1]);
};

const SKIP_DIRS = new Set(['node_modules', 'dist', 'assets', '.git', 'print']);
async function walk(dir) {
  for (const name of await readdir(dir)) {
    if (name.startsWith('.') || SKIP_DIRS.has(name)) continue;
    const p = join(dir, name);
    if ((await stat(p)).isDirectory()) { await walk(p); continue; }
    if (name.endsWith('.jsx') || name.endsWith('.js') || name.endsWith('.html')) {
      addFrom(await readFile(p, 'utf8'));
    }
  }
}
await walk(ROOT);

// ---- 2. load the vendor bundle and pull the needed definitions
const src = await readFile(VENDOR, 'utf8');
const win = {};
const mod = { exports: {} };
const stubDoc = { createElement: () => ({ setAttribute() {}, appendChild() {} }), querySelectorAll: () => [] };
new Function('window', 'self', 'globalThis', 'module', 'exports', 'document', src)(win, win, win, mod, mod.exports, stubDoc);
const all = (win.lucide || mod.exports).icons;

const pascal = (kebab) => kebab.split('-').map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('');
const picked = {};
const missing = [];
for (const n of [...names].sort()) {
  const key = pascal(n);
  if (all[key]) picked[n] = all[key];
  else missing.push(n);
}

// ---- 3. emit the subset + a minimal createIcons compatible with the app's usage
//        (app calls window.lucide.createIcons() with no args, repeatedly).
const body = `/* lucide subset — ${Object.keys(picked).length} icons, generated by scripts/build-icons.mjs. Do not edit. */
(function () {
  var I = ${JSON.stringify(picked)};
  var BASE = { xmlns: 'http://www.w3.org/2000/svg', width: 24, height: 24, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 2, 'stroke-linecap': 'round', 'stroke-linejoin': 'round' };
  function build(name, el) {
    var def = I[name];
    if (!def) return null;
    var svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    for (var k in BASE) svg.setAttribute(k, BASE[k]);
    svg.setAttribute('class', 'lucide lucide-' + name);
    // carry over the author's presentational attributes (size, style, aria)
    for (var i = 0; i < el.attributes.length; i++) {
      var a = el.attributes[i];
      if (a.name === 'data-lucide') continue;
      if (a.name === 'class') { svg.setAttribute('class', 'lucide lucide-' + name + ' ' + a.value); continue; }
      svg.setAttribute(a.name, a.value);
    }
    for (var j = 0; j < def.length; j++) {
      var child = document.createElementNS('http://www.w3.org/2000/svg', def[j][0]);
      var attrs = def[j][1] || {};
      for (var p in attrs) child.setAttribute(p, attrs[p]);
      svg.appendChild(child);
    }
    return svg;
  }
  function createIcons() {
    var els = document.querySelectorAll('[data-lucide]');
    for (var i = 0; i < els.length; i++) {
      var el = els[i];
      var svg = build(el.getAttribute('data-lucide'), el);
      if (svg && el.parentNode) el.parentNode.replaceChild(svg, el);
    }
  }
  window.lucide = { createIcons: createIcons, icons: I };
})();
`;
await writeFile(OUT, body, 'utf8');

const before = src.length, after = body.length;
console.log(`lucide subset: ${Object.keys(picked).length} icons — ${(after / 1024).toFixed(1)} KB (was ${(before / 1024).toFixed(1)} KB, ${(100 - (after / before) * 100).toFixed(1)}% smaller)`);
if (missing.length) console.log(`  note: ${missing.length} scanned names are not lucide icons (route ids etc.), ignored`);
